### ISSUE TITLE
Our Story desktop app first time start fails when not connected to internet

### ISSUE THREAD

**Issue by delvinv** [our-story-media/ourstory-titan#5]
Our Story desktop app first time start fails when not connected to internet. The option to load images.tar is there but as soon as it is selected, it gives an error: host not found download.docker.com. But as soon as i make machine online the installer works fine and installs and starts Docker. 

I guess it is an issue if we say to people you dont need internet as long as you have these 2 things on a USB stick, but if they still need to be online to install then it changes the scenario a bit!

**Comment by delvinv** [comment]
Also Our Story app needs to be run as an administrator, otherwise it doesnt open. Any way to make it open as admin by default?

**Comment by tombartindale** [comment]
> Also Our Story app needs to be run as an administrator, otherwise it doesnt open. Any way to make it open as admin by default?

This does happen on Win10. Its a known issue on win7.
